controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

navbar:
    path:       /
    controller: App\Controller\NavbarController::index

login:
    path:
        controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    methods: POST