controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

navbar:
    path:       /
    controller: App\Controller\NavbarController::index

login:
    path:
        controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    methods: POST

app_user_profile_index:
    path:
        controller: App\Controller\UserProfileController:index

app_user_profile_show:
    path: '/user/{username}'
    methods: GET
    controller: App\Controller\UserProfileController::show

app_starter_page:
    path:
        controller: App\Controller\StarterPageController::index

app_friends:
    path:
        controller: App\Controller\FriendsController::index

app_friends_show:
    path:
        controller: App\Controller\FriendsController::show

app_add_friends:
    path: '/friends/add/{id}/{username}'
    methods: POST
    controller: App\Controller\FriendsController::add

app_friends_set:
    path: '/friends/set/{id}'
    controller: App\Controller\FriendsController::set

app_invitations:
    path: '/invitations/show'
    controller: App\Controller\InvitationsController::index

app_invitations_accept:
    path: '/invitations/accept/{id}'
    methods: GET
    controller: App\Controller\InvitationsController::accept


app_invitations_rejected:
    path: '/invitations/rejected/{id}'
    methods: GET
    controller: App\Controller\InvitationsController::rejected


app_messages_send:
    path : '/messages/'
    methods: POST
    controller: App\Controller\MessagesController::add
