controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

navbar:
    path:       /
    controller: App\Controller\NavbarController::index

login:
    path:
        controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    methods: POST

app_user_profile_index:
    path:
        controller: App\Controller\UserProfileController:index

app_user_profile_show:
    path: '/{username}'
    methods: GET
    controller: App\Controller\UserProfileController::show

app_starter_page:
    path:
        controller: App\Controller\StarterPageController::index

app_friends:
    path:
        controller: App\Controller\FriendsController::index

app_add_friends:
    path: '/{id}/{username}'
    methods: POST
    controller: App\Controller\FriendsController::add
